name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download TryHackMe badge
        run: |
          curl -o assets/tryhackme-badge.png https://tryhackme-badges.s3.amazonaws.com/nazhiba..png
      - name: Commit and push if badge changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/tryhackme-badge.png
          git diff --cached --quiet || git commit -m "Update TryHackMe badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}